General refactor
ElrondNetwork/elrond-deploy-go pull request #42
Opened 2021-01-06 00:11 UTC by iulianpascalau

- complete refactor of the solution: split functionality in packages and structures, added unit/semi-integration unit tests

2021-01-06 09:26 UTC, bogdan-rosianu requested changes

2021-01-06 11:31 UTC, iulianpascalau commented on checking/errors.go
> +// ErrEmptyInitialAccounts signals that an empty initial accounts list
done

2021-01-06 11:32 UTC, iulianpascalau commented on checking/errors.go
> +// ErrSupplyMismatch signals that the initial account's supply mismatches
rephrased

2021-01-06 11:32 UTC, iulianpascalau commented on checking/errors.go
> +// ErrTotalSupplyMismatch signals that the total supply mismatches
rephrased

2021-01-06 11:33 UTC, iulianpascalau commented on cmd/filegen/main.go
> +		Value: 3,
I would keep them as they are as we won't test for now with 5 shards. Will update the readme.md also

2021-01-06 11:37 UTC, iulianpascalau commented on core/converters.go
> +	if valueNumber.Cmp(big.NewInt(0)) < 0 {
Agree, changed the function name to `ConvertToPositiveBigInt`

2021-01-06 11:37 UTC, iulianpascalau commented on core/converters.go
> +
done

2021-01-06 11:40 UTC, iulianpascalau commented on core/converters_test.go
> +	require.Nil(t, err)
no necessarily true. We can have both. Last checks can be asserts if they can't panic. I have followed the rule: if the test can panic in an assert (due to nils or whatever), the preceding check(s) should be done with require. Having as many as asserts we can put will throw all errors at once. The use of require will stop at each error (the test will stop there). In some cases it is better to see all errors (or as much errors as we can get) in order to easily debug the code.

2021-01-06 11:41 UTC, iulianpascalau commented on core/fileHandler.go
> +// IsInterfaceNil returns if underlying object is true
fixed all of them :+1:

2021-01-06 11:41 UTC, iulianpascalau commented on generating/delegatedGenerator.go
> +// IsInterfaceNil returns if underlying object is true
done

2021-01-06 11:43 UTC, iulianpascalau commented on generating/delegatedGenerator_test.go
> +	arg.NumValidatorBlsKeys = 33
used args fields as variables

2021-01-06 11:43 UTC, iulianpascalau commented on generating/directStakingGenerator.go
> +// IsInterfaceNil returns if underlying object is true
done

2021-01-06 11:44 UTC, iulianpascalau commented on generating/directStakingGenerator_test.go
> +	arg.NumValidatorBlsKeys = 33
done

2021-01-06 11:45 UTC, iulianpascalau commented on generating/disabled/nilRandomizer.go
> +// IsInterfaceNil returns if underlying object is true
done

2021-01-06 11:55 UTC, iulianpascalau commented on generating/validatorKeyGenerator.go
> +package generating
renamed: `generate` and `check`

2021-01-06 12:04 UTC, iulianpascalau commented on io/errors.go
> +package io
renamed to plugins.

2021-01-06 12:04 UTC, iulianpascalau commented on io/outputHandler.go
> +// writeGenesisFile will write the provided initial accounts in to the genesis file
removed

2021-01-06 12:04 UTC, iulianpascalau commented on io/outputHandler.go
> +// IsInterfaceNil returns if underlying object is true
done

2021-01-06 12:05 UTC, iulianpascalau commented on io/txgenAccount.go
> +type txgenAccount struct {
Will move it if we need it in some other places. This struct is used only in the plugins package and it is not a business logic core data structure.

2021-01-07 08:54 UTC, bogdan-rosianu approved these changes

2021-01-07 10:45 UTC, BeniaminDrasovean approved these changes

2021-01-07 15:51 UTC, merged