New elrond-go v1.2.32
ElrondNetwork/elrond-deploy-go pull request #46
Opened 2021-11-08 11:29 UTC by iulianpascalau

- adaptations to new elrond-go v1.2.32

2021-11-08 16:30 UTC, raduchis submitted a review, later dismissed

2021-11-09 06:59 UTC, sasurobert approved these changes

2021-11-09 07:00 UTC, bogdan-rosianu requested changes

2021-11-09 07:01 UTC, iulianpascalau commented on README.md
> +$ ./filegen -stake-type delegated -node-price 2500000000000000000000 -total-supply 20000000000000000000000000 -num-of-shards 3 -num-of-nodes-in-each-shard 7 -consensus-group-size 5 -num-of-observers-
:facepalm:

2021-11-09 07:02 UTC, bogdan-rosianu approved these changes

2021-11-09 07:06 UTC, sasurobert approved these changes

2021-11-09 07:12 UTC, raduchis approved these changes

2021-11-09 07:17 UTC, merged